name: Build and Push to ACR
on:
  push:
    branches:
      - "main"
jobs:
  build:
    name: "Build and Push to ACR"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: build and push to ACR
        run: |
          # az acr build --registry mibancoacr --image mibanco:${{ github.sha }} --file app/Dockerfile .
          az acr login --name mibancoacr

          ACR_NAME=$(az acr show -n mibancoacr --query loginServer -o tsv)

          docker build -t $ACR_NAME/mibanco:${GITHUB_SHA} -f app/Dockerfile .
          docker push $ACR_NAME/mibanco:${GITHUB_SHA}

      # - name: Docker Login
      #   uses: azure/docker-login@v1
      #   with:
      #     login-server: ${{ secrets.AZURE_URL }}
      #     username: ${{ secrets.ACR_USERNAME }}
      #     password: ${{ secrets.ACR_PASSWORD }}

      # - name: Build and Push to ACR
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: ${{ github.sha }}
      #     file: app/Dockerfile

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubectl
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

      - run: |
          echo "Current directory: $(pwd)"
          echo $(ls -a)

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yml
          kubectl apply -f k8s/hpa.yml
